apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: javaspring
        image: malleshdevops/devops14-project:java-v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /application.properties
          subPath: application.properties
          name: java-config-volume
      volumes:
      - configMap:
          name: java-config
          items:
            - key: application.properties
              path: application.properties
        name: java-config-volume
