apiVersion: v1
kind: Service
metadata:
  name: react-lb
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
